# Processing pipeline configuration

# Define some shorthands to avoid repetition
survey_dir: "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Full Weighted 2023 Dataset/WeightedDataset_02212025"
output_dir: "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/BATS2023"

# Function as a state-driven processing pipeline
# Meaning that the canonical tables (household, person, trip, tour) are passed between steps and modified in place
# Intermediate files are not written to disk, unless explicitly specified in a step

pipeline:
  steps:
    - name: cleaning
      inputs:
        household: "{{ survey_dir }}/household.csv"
        person: "{{ survey_dir }}/person.csv"
        unlinked_trip: "{{ survey_dir }}/trip.csv"
        tour: "{{ survey_dir }}/tour.csv"
        taz: "X:/travel-model-one-master/utilities/geographies/bayarea_rtaz1454_rev1_WGS84.shp"
      # No outputs, pass data between steps internally
      # outputs:
      #   cleaned_data: "{{ output_dir }}/cleaned_data.csv"

    - name: linking
      # No inputs, use output from previous step
      # input: processed_data/cleaned_data.csv

    - name: tour_building

    - name: formatting
      output:
        household: "{{ output_dir }}/households.csv"
        person: "{{ output_dir }}/persons.csv"
        day: "{{ output_dir }}/days.csv"
        unlinked_trips: "{{ output_dir }}/unlinked_trips.csv"
        linked_trips: "{{ output_dir }}/linked_trips.csv"
